Xm.Trial/Models/BlogViewModel.cs
using System.Collections.Generic;

namespace Xm.Trial.Models
{
    public class BlogViewModel
    {
        public string Title { get; set; }
        public ICollection<PostSnippetViewModel> Posts { get; set; }
    }
}

Xm.Trial/Models/ContactUsForm.cs
namespace Xm.Trial.Models
{
    public class ContactUsForm
    {
        public string Email { get; set; }

        public string Message { get; set; }
    }
}

Xm.Trial/Models/Data/Author.cs
using System;
using System.ComponentModel.DataAnnotations;

namespace Xm.Trial.Models.Data
{
    public class Author
    {
        [Key]
        public int Id { get; set; }

        [MaxLength(150)]
        public string Name { get; set; }

        [MaxLength(400)]
        public string Avatar { get; set; }

        public DateTimeOffset Registered { get; set; }
    }
}

Xm.Trial/Models/Data/DataContext.cs
using System.Data.Entity;

namespace Xm.Trial.Models.Data
{
    public class DataContext : DbContext
    {
        public DbSet<Post> Posts{ get; set; }
        public DbSet<Tag> Tags { get; set; }
        public DbSet<Author> Authors { get; set; }
    }
}

Xm.Trial/Models/Data/Post.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Xm.Trial.Models.Data
{
    public class Post
    {
        [Key]
        public int Id { get; set; }

        public int AuthorId { get; set; }

        public DateTimeOffset Created { get; set; }

        public string Title { get; set; }

        public string Picture { get; set; }

        public string PictureCaption { get; set; }

        public string Text { get; set; }

        public string Snippet { get; set; }

        public int Likes { get; set; }

        [ForeignKey(nameof(AuthorId))]
        public Author Author { get; set; }

        public ICollection<Tag> Tags { get; set; }
    }
}

Xm.Trial/Models/Data/Tag.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace Xm.Trial.Models.Data
{
    public class Tag
    {
        [Key]
        public int Id { get; set; }

        [MaxLength(75)]
        public string Name { get; set; }

        public ICollection<Post> Posts { get; set; }
    }
}

Xm.Trial/Models/IPostViewModel.cs
using System;
using Xm.Trial.Models.Data;

namespace Xm.Trial.Models
{
    public interface IPostViewModel
    {
        Author Author { get; set; }
        DateTimeOffset Created { get; set; }
        int Id { get; set; }
        string Title { get; set; }
    }
}

Xm.Trial/Models/LikeViewModel.cs
namespace Xm.Trial.Models
{
    public class LikeViewModel
    {
        public int Id { get; set; }
        public int Count { get; set; }
    }
}

Xm.Trial/Models/PostSnippetViewModel.cs
using System;
using Xm.Trial.Models.Data;

namespace Xm.Trial.Models
{
    public class PostSnippetViewModel : IPostViewModel
    {
        public int Id { get; set; }

        public DateTimeOffset Created { get; set; }

        public string Title { get; set; }

        public string Picture { get; set; }

        public string PictureCaption { get; set; }

        public string Snippet { get; set; }

        public Author Author { get; set; }
    }
}

Xm.Trial/Models/PostViewModel.cs
using System;
using System.Collections.Generic;
using Xm.Trial.Models.Data;

namespace Xm.Trial.Models
{
    public class PostViewModel : IPostViewModel
    {
        public int Id { get; set; }

        public DateTimeOffset Created { get; set; }

        public string Title { get; set; }

        public string Picture { get; set; }

        public string PictureCaption { get; set; }

        public string Text { get; set; }

        public int Likes { get; set; }

        public Author Author { get; set; }

        public ICollection<Tag> Tags { get; set; }
    }
}

Xm.Trial/Controllers/AboutController.cs
using System.Web.Mvc;

namespace Xm.Trial.Controllers
{
    public class AboutController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }
    }
}

Xm.Trial/Controllers/Api/LikeController.cs
using System.Threading.Tasks;
using System.Web.Http;
using Xm.Trial.Models;
using Xm.Trial.Models.Data;

namespace Xm.Trial.Controllers.Api
{
    public class LikeController : ApiController
    {
        private readonly DataContext _db = new DataContext();

        [HttpPost]
        public async Task<IHttpActionResult> Like(int id)
        {
            var post = await _db.Posts.FindAsync(id);

            if (post == null)
                return NotFound();

            post.Likes++;

            await _db.SaveChangesAsync();

            var viewModel = new LikeViewModel
                            {
                                Id = post.Id,
                                Count = post.Likes
                            };

            return Ok(viewModel);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
                _db.Dispose();

            base.Dispose(disposing);
        }
    }
}

Xm.Trial/Controllers/BlogController.cs
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Web.Mvc;
using Xm.Trial.Models;
using Xm.Trial.Models.Data;

namespace Xm.Trial.Controllers
{
    public class BlogController : Controller
    {
        private readonly DataContext _db = new DataContext();

        public async Task<ActionResult> Index()
        {
            var posts = await _db.Posts
                                 .Select(p => new PostSnippetViewModel
                                              {
                                                  Id = p.Id,
                                                  Created = p.Created,
                                                  Title = p.Title,
                                                  Picture = p.Picture,
                                                  PictureCaption = p.PictureCaption,
                                                  Snippet = p.Snippet,
                                                  Author = p.Author
                                              })
                                 .ToArrayAsync();

            var viewModel = new BlogViewModel
                            {
                                Title = "Posts",
                                Posts = posts
                            };

            return View(viewModel);
        }

        public async Task<ActionResult> Details(int id)
        {
            var post = await _db.Posts
                                .Select(p => new PostViewModel
                                             {
                                                 Id = p.Id,
                                                 Created = p.Created,
                                                 Title = p.Title,
                                                 Picture = p.Picture,
                                                 PictureCaption = p.PictureCaption,
                                                 Text = p.Text,
                                                 Likes = p.Likes,
                                                 Author = p.Author,
                                                 Tags = p.Tags
                                             })
                                .FirstOrDefaultAsync(p => p.Id == id);

            if (post == null)
                return new HttpNotFoundResult();

            ViewBag.Title = post.Title;

            return View(post);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
                _db.Dispose();

            base.Dispose(disposing);
        }
    }
}

Xm.Trial/Controllers/ContactUsController.cs
using System.Web.Mvc;

namespace Xm.Trial.Controllers
{
    public class ContactUsController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }
    }
}

Xm.Trial/Views/About/Index.cshtml
<h2>About</h2>

<p>
    Lorem ipsum dolor sit amet, consectetur adipisicing elit. Debitis doloremque ipsa magni ut voluptatem! Dicta ducimus
    ipsa iste minus nemo! Amet at ea labore molestiae, pariatur placeat quos repudiandae vitae!
</p>
<p>
    Ad aliquid
    aspernatur aut cumque debitis dolorem dolores eius excepturi, facere fuga ipsum minima molestias natus nesciunt
    omnis quas quo rerum saepe, tempore veritatis! Eos fugiat molestias sed sequi veniam.
</p>
<p>
    Accusantium architecto,
    blanditiis enim eos error est fugit illum iure iusto, laudantium maiores nulla officia perferendis quod sunt
    temporibus voluptate! Delectus dignissimos hic ipsa molestiae necessitatibus nobis obcaecati tempora. Expedita!
</p>
<p>
    Accusantium aut beatae blanditiis deleniti dicta doloremque eos esse est eveniet ex inventore labore magnam nostrum
    optio, pariatur provident quod reiciendis reprehenderit sapiente soluta totam ullam vel veritatis voluptas
    voluptatibus.
</p>
<p>
    Alias aspernatur assumenda aut consequatur, cupiditate doloremque doloribus eius error ipsa,
    iusto laudantium molestias neque nisi non nostrum officia officiis perferendis ratione veritatis voluptatum! Illum
    ipsa placeat quod sint vero!
</p>

Xm.Trial/Views/Blog/Details.cshtml
@model Xm.Trial.Models.PostViewModel

@{
    ViewBag.Title = Model.Title;
}

<article>
    <header>
        <h1>@Model.Title</h1>
        @Html.Partial("PostMeta")
    </header>

    <figure>
        <img src="@Model.Picture" alt="@Model.Title">
        <figcaption>@Model.PictureCaption</figcaption>
    </figure>

    @Html.Raw(Model.Text)
       
    <footer>
        <p>
            <button data-action="like" data-post-id="@Model.Id">@Model.Likes</button>
        </p>

        @if (Model.Tags?.Any() == true)
        {
            <small>
                @foreach (var tag in Model.Tags)
                {
                    <a href="@Url.Action("Index", "Blog", new RouteValueDictionary { ["tag"] = tag.Id })" class="tag">@tag.Name</a>
                }
            </small>
        }
    </footer>
</article>

Xm.Trial/Views/Blog/Index.cshtml
@model Xm.Trial.Models.BlogViewModel

@{
    ViewBag.Title = Model.Title;
}

@foreach (var post in Model.Posts)
{
    var detailsUrl = Url.Action("Details", new RouteValueDictionary { ["id"] = post.Id });

    <article>
        <header>
            <h2><a href="@detailsUrl">@post.Title</a></h2>
            @Html.Partial("PostMeta", post)
        </header>
        
        <a href="@detailsUrl">
            <figure>
                <img src="@post.Picture" alt="@post.Title">
                <figcaption>@post.PictureCaption</figcaption>
            </figure>
        </a>

        <p>@post.Snippet</p>
    </article>
}

Xm.Trial/Views/Blog/PostMeta.cshtml
@model Xm.Trial.Models.IPostViewModel

<section class="post-meta">
    @if (Model.Author != null)
            {
        <address class="author">By <img src="@Model.Author.Avatar"> @Model.Author.Name</address>
    }
    <time datetime="@Model.Created.ToString("o")">@Model.Created.ToString("D")</time>
</section>

Xm.Trial/Views/ContactUs/Index.cshtml
<h2>Contact Us</h2>

Xm.Trial/Views/Shared/Menu.cshtml
<nav class="main-menu">
    <ul>
        <li><a href="@Url.Action("Index", "Blog")">Blog</a></li>
        <li><a href="@Url.Action("Index", "About")">About us</a></li>
        <li><a href="@Url.Action("Index", "ContactUs")">Contact us</a></li>
    </ul>
</nav>

Xm.Trial/Views/Shared/_Layout.cshtml
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>
    
    @Styles.Render("~/Content/bundles/css")
</head>
<body>
    <header>Blog</header>

    @Html.Partial("Menu")
    
    <main>
        @RenderBody()
    </main>
    
    <footer>
        <small>
            Copyright © @DateTime.UtcNow.Year blog. All rights reserved
        </small>
    </footer>

    @Scripts.Render("~/Content/bundles/js")
</body>
</html>